### ISSUE TITLE
DriveTank end should use stop

### ISSUE THREAD

**Issue by TomerSitton** [Spikes-2212-Programming-Guild/Spikes-Lib#68]
https://github.com/Spikes-2212-Programming-Guild/Spikes-Lib/blob/755600c555dd80190b8e6b19ef384924d4429598/src/com/spikes2212/genericsubsystems/drivetrains/commands/DriveTank.java#L68

the end method in the DriveTank command should use TankDrivetrain.stop() instead of set(0,0)

**Comment by YonatanNitzan** [comment]
Fixed the same issue in DriveArcade and DriveHolonomic
